# Enabling the new cops
AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

# Adding exceptions to Rubocop's offenses
Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
